kind = "web"
previewPath = "/"
title = "Insta-Study"
version = "1.0.0"
id = "artifacts/insta-study"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22451

[services.development]
run = "pnpm --filter @workspace/insta-study run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/insta-study", "run", "build" ]
publicDir = "artifacts/insta-study/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22451"
BASE_PATH = "/"
